[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 115200
lib_ldf_mode = chain+
lib_deps =
    jgromes/RadioLib@7.6.0
    knolleary/PubSubClient@2.8
    ssilverman/QNEthernet
build_flags =
    -std=c++17
    -DTEENSY=41
